apiVersion: v1
kind: Pod
metadata:
  name: busybox-with-pvc
spec:
  containers:
    - name: busbox
      image: busybox
#      command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 2 ; done"]
      command: ['tail', '-f', '/dev/null']
      volumeMounts:
        - mountPath: /mnt/test
          name: vol
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: test-pvc
