apiVersion: v1
kind: Pod
metadata:
  name: python
  labels:
    app: python
spec:
  containers:
    - name: python
      image: python
      ports:
        - containerPort: 8000
#          hostPort: 8080
      command: ['python', '-m', 'http.server', '--directory=/', '--bind=0.0.0.0']
