apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: simple-cluster
spec:
  kafka:
    version: 3.3.1
    replicas: 2
#    authorization:
#      type: simple
#      superUsers:
#        - admin-scram
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
#      - name: ext1
#        port: 9094
#        type: nodeport
#        tls: false
#      - name: extscram
#        port: 9095
#        type: internal
#        tls: false
#        authentication:
#          type: scram-sha-512
#    resources:
#      requests:
#        memory: 2Gi
#        cpu: "0.5"
#      limits:
#        memory: 2Gi
#        cpu: "1"
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.3"
      num.partitions: 3
#      log.retention.ms: 2592000000
#      offset.retention.minutes: 20160
#      compression.type: zstd
      message.max.bytes: 10000000
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 5Gi
          deleteClaim: false
#    template:
#      pod:
#        tmpDirSizeLimit: 50Mi #default is 1 or 5 and too small
#        affinity:
#          podAntiAffinity:
#            requiredDuringSchedulingIgnoredDuringExecution:
#              - labelSelector:
#                  matchExpressions:
#                    - key: strimzi.io/name
#                      operator: In
#                      values:
#                        - my-cluster
#                topologyKey: "kubernetes.io/hostname"
#          nodeAffinity:
#            requiredDuringSchedulingIgnoredDuringExecution:
#              nodeSelectorTerms:
#                - matchExpressions:
#                    - key: node.kubernetes.io/instance-type
#                      operator: In
#                      values:
#                        - c5a.2xlarge
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
